package org.fpsrobotics.actuators.manipulator;

public enum ManipulatorPreset
{
	LOW_BAR, SHOOT_HIGH_CORNER, SHOOT_HIGH_CENTER, SHOOT_LOW, STANDARD_DEFENSE, LIFTER_AUGER_MOVEMENTS, POSITION_TWO_AUTO, POSITION_THREE_AUTO, POSITION_FOUR_AUTO, POSITION_FIVE_AUTO, FOURTY_KAI;
}
